// <auto-generated />
namespace CrudWithEntityFrameworkApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initlizeDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initlizeDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202012120701564_initlizeDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
